server:
  port: 8080
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-ForWarded-Proto
  forward-headers-strategy: native
spring:
  profiles:
    active: dev
  datasource:
    username: ENC(eIjJJ4k5QJPg1W6gCDfNGZKwgcaw3fizKIcEVWfrj4uUvIB5PK4jDN6Em9NieLC1)
    password: ENC(ygNRobuqcsWi9+1I99rgKb1rHPt907THOt0dDWosN3KjnRmYfTsMp3EVaqVtw0qn)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

  mail:
    properties.mail.smtp.ssl: true
    host: smtp.163.com
    username: ENC(wCNLxDvgij/aBZVKOkhXeh1RLvCsInaL7ZkOfpd3jN9+wXU/Vz/8/kmlJAjeG/XMHLXUs6yhGWAmBZt6vUKqLQ==)
    password: ENC(PZuN6IyuAumgqn5wAvHvZ/vpECd1P+U9WORy90NkNOlIxhmwaZEwNVRED5Pmvnyq)

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置 可以是类路径下的，还可以是网络路径或者是磁盘路径
  # 在xml配置文件中，可以通过resource和url分别指定不同的情况
  mapper-locations: classpath:mappers/*.xml

qiniu:
  Host: ENC(u+UGWnQSgLWW2gfL1ElmZf0tfCC172O1FFlgf2j0pRpDjZri5JUAtWMA7jY4ujGonoEBs4ITmDkiFWte+JaAjONul3tWwJaHRjoDpe9xzVg=)
  AccessKey: ENC(I+8+a2Wk63YiJvUWd3OtFTAQ5qgNsx0gIITzdHs79sxeVNNROOTUZ1S9gnZefs4VqPGK3SDqHNfgT4DKwLAcGghFRVpOySsSEkufjFjWSH4=)
  SecretKey: ENC(eIAl6AuS2pSO+e/eQMePJaNHHIL6liF7h9SB8sNpwfdBlhT5Pj/DuttsTl853OvBtyRTb8ZRTg8FSclYLxgZSYlIk4OA4mM8Iw/H8FAYa+w=)
  Bucket: ENC(FdfmHPtDbyUyiMfCsEDY36S4YSBQHDYy4GUPaweEtHuObPlVTJfuSS4uvtH9iE1G)
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql