logging:
  config: classpath:logging-back-dev.xml
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.0.102/blog?serverTimezone=Asia/Shanghai&useSSL=false&&characterEncoding=utf8&&useAffectedRows=true